name: face-api-venv
channels:
  - conda-forge
dependencies:
  - face_recognition
  - fastapi
  - uvicorn
  - python-multipart
  - requests
  - numpy
  - pillow
  - python-multipart
  - pymongo[srv]==4.9.1